# Generated by Django 5.1.2 on 2024-11-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissionevents",
            name="emissions_limit",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="emissionevents",
            name="emissions_rate",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="emissionevents",
            name="estimated_quantity",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="emissionevents",
            name="hours_elapsed",
            field=models.TextField(),
        ),
    ]
