# Generated by Django 5.1.2 on 2025-02-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_superfundsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionevents',
            old_name='emissions_limit',
            new_name='contaminant_emissions_limit',
        ),
        migrations.RenameField(
            model_name='emissionevents',
            old_name='limit_units',
            new_name='contaminant_emissions_limit_units',
        ),
        migrations.RenameField(
            model_name='emissionevents',
            old_name='estimated_quantity',
            new_name='contaminant_est_quantity',
        ),
        migrations.AddField(
            model_name='emissionevents',
            name='authorization',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emissionevents',
            name='contaminant_est_quantity_units',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superfundsite',
            name='epa_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
