# Generated by Django 5.1.2 on 2025-02-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_superfundsite"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissionevents",
            name="actions_taken",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="authorization_comment",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="basis_used",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="cause",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="emission_point_name",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="epn",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="event_type",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="initial_notice",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="region_id",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="registration",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emissionevents",
            name="flag",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="superfundsite",
            name="epa_id",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
