# Generated by Django 5.1.2 on 2025-02-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_superfundsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='superfundsite',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='superfundsite',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='superfundsite',
            name='epa_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
