# Generated by Django 5.1.2 on 2025-02-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_emissionevents_actions_taken_and_more"),
        ("main", "0004_superfundsite_lat_superfundsite_lon_and_more"),
    ]

    operations = []
