# Generated by Django 5.1.2 on 2025-02-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_emissionevents_latitude_emissionevents_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionevents',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='emissionevents',
            name='longitude',
        ),
        migrations.AddField(
            model_name='superfundsite',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superfundsite',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
