# Generated by Django 5.1.2 on 2025-02-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_emissions_limit_emissionevents_contaminant_emissions_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionevents',
            name='contaminant_est_quantity_units',
        ),
        migrations.AlterField(
            model_name='emissionevents',
            name='authorization',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='emissionevents',
            name='contaminant_emissions_limit',
            field=models.TextField(default=''),
        ),
    ]
