# Generated by Django 5.1.2 on 2025-02-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_merge_20250222_2012"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emissionevents",
            name="emissions_limit",
        ),
        migrations.RemoveField(
            model_name="emissionevents",
            name="estimated_quantity",
        ),
        migrations.RemoveField(
            model_name="emissionevents",
            name="limit_units",
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="authorization",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="contaminant_emissions_limit",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="contaminant_emissions_limit_units",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="contaminant_est_quantity",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emissionevents",
            name="contaminant_est_quantity_units",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
    ]
