# Generated by Django 5.1.2 on 2025-02-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_emissionevents_contaminant_est_quantity_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionevents',
            name='contaminant_est_quantity_units',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='emissionevents',
            name='contaminant_emissions_limit',
            field=models.TextField(),
        ),
    ]
