# Generated by Django 5.1.2 on 2025-02-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20250222_2025'),
        ('main', '0007_merge_20250222_2036'),
    ]

    operations = [
    ]
