# Generated by Django 5.1.2 on 2025-03-29 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_emissionevents_emissions_limit_and_more'),
        ('main', '0008_merge_20250222_2151'),
    ]

    operations = [
    ]
