# Generated by Django 5.1.2 on 2025-04-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_emissionevents_emissions_limit_and_more'),
        ('main', '0008_merge_20250222_2151'),
    ]

    operations = [
    ]
