# Generated by Django 5.1.2 on 2025-04-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_merge_20250329_1902"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissionevents",
            name="authorization",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="emissionevents",
            name="contaminant_est_quantity_units",
            field=models.TextField(default=""),
        ),
    ]
