# Generated by Django 5.1.2 on 2025-04-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20250412_2018'),
        ('main', '0010_alter_emissionevents_authorization_and_more'),
    ]

    operations = [
    ]
