name: Run Scraper Daily

on:
  push:
    branches:
      - scraper-tecq
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual workflow trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Use your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
          # Ensure chromedriver is in PATH
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver
        env:
          CHROME_BIN: "/usr/bin/google-chrome"
          CHROMEDRIVER_PATH: "/usr/local/bin/chromedriver"

      - name: Verify ChromeDriver Installation
        run: |
          which chromedriver
          chromedriver --version

      - name: Run Scraper
        env:
          CHROME_BIN: "/usr/bin/google-chrome"
          CHROMEDRIVER_PATH: "/usr/local/bin/chromedriver"
        run: |
          python main.py

      - name: Save Excel Output
        run: |
          timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
          mv output.xlsx "output_$timestamp.xlsx"
          mv "output_$timestamp.xlsx" results/

      - name: Commit and Push the Excel file
        run: |
          git config --local user.email "nn36@rice.edu"
          git config --local user.name "GitHub Actions"
          git add results/output_*.xlsx
          git commit -m "Add data for $timestamp"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
